name: PMD Source Code Analyzer on Push

on: [push]

jobs:
  pmd:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
 
      - uses: Moose0621/setup-pmd@v2
      
      - name: run-pmd
        run: |
          ls -la; ls -la ../
          pmd -d webgoat-container/,webgoat-server -failOnViolation false -f sarif -R rulesets/java/quickstart.xml > results.sarf
          
      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
